#Your workflow name
name : Deploy to Heroku.

#Run workflow on every push to the main branch
on:
  push:
    branches: [main]
  
#Your workflow jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository
      - name: Checkout
        uses: actions/checkout@v2

### Important Part ###

      - name: Build, Push and Release a Docker container to Heroku. # your custom
        uses: gonuit/heroku-docker-deploy@v1.3.3 #Github action name (Leave it as it is)
        with:
          ## Add all these details in Github actions
          email: ${{ secrets.HEROKU_EMAIL}}

          heroku_api_key: ${{ secrets.HEROKU_API_KEY}}

          heroku_app_name: ${{ secrets.HEROKU_APP_NAME}}

          dockerfile_directory : ./

          dockerfile_name : Dockerfile

          docker_options: "--no-cache"

          process_type: web

### Important Part ###
